version: 1
disable_existing_loggers: True
retain_logs_days: 30

formatters:
  report:
    format: "[%(asctime)s]---%(levelname)s---||%(module)s.%(funcName)s.ln:%(lineno)s||%(message)s"
    datefmt: '%H:%M:%S'
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "[%(asctime)s] %(levelname)s: %(message)s"
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: report
  filehandler:
    class: logging.FileHandler
    encoding: utf-8
    delay: true
    formatter: report
    filename: log.log
  m_filehandler:
    class: logging.handlers.RotatingFileHandler
    encoding: utf-8
    delay: true
    formatter: extended
    filename: log.log
    maxBytes: 1048576 # 10MB
    backupCount: 5
    
loggers:
  master:
    level: 10 # 20 = info, 10 = debug
    handlers: [console,m_filehandler]
    propogate: yes
  main:
    level: 10 # 20 = info, 10 = debug
    handlers: [console,filehandler]
    propogate: yes